name: sample_dbt
version: '1.0'
config-version: 2

profile: sample_dbt

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

# PR環境でのデータセット作成を有効化
on-run-start:
  - "{{ create_schema_if_not_exists() }}"

models:
  sample_dbt:
    +materialized: view
    staging:
        +materialized: view
        +schema: "staging"
    marts:
        +materialized: table
        +schema: "marts"
