name: sample_dbt
version: '1.0'
config-version: 2

profile: sample_dbt

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  sample_dbt:
    +materialized: view
    +schema: "{{ generate_schema_name_with_env(this.schema) }}"
    staging:
        +materialized: view
        +schema: "{{ generate_schema_name_with_env('staging') }}"
    marts:
        +materialized: table
        +schema: "{{ generate_schema_name_with_env('marts') }}"
