version: 2

sources:
  - name: test_dbt_cloud
    description: "サンプルソースシステムのデータ"
    schema: test_dbt_cloud
    tables:
      - name: table1
        description: "顧客情報テーブル"
        columns:
          - name: id
            description: "顧客ID（プライマリキー）"
            tests:
              - unique
              - not_null
          - name: column_a
            description: "顧客名"
          - name: column_b
            description: "部署名"
          - name: created_at
            description: "作成日時"
          - name: updated_at
            description: "更新日時"
      - name: products
        description: "製品マスターテーブル"
        columns:
          - name: product_id
            description: "製品ID（プライマリキー）"
            tests:
              - unique
              - not_null
          - name: product_name
            description: "製品名"
          - name: category
            description: "カテゴリ"
          - name: price
            description: "価格"
          - name: stock_quantity
            description: "在庫数"
          - name: supplier_id
            description: "サプライヤーID"
          - name: description
            description: "製品説明"
          - name: created_at
            description: "作成日時"
          - name: updated_at
            description: "更新日時（スナップショット用）"
            tests:
              - not_null
      
      - name: orders
        description: "注文データテーブル"
        columns:
          - name: order_id
            description: "注文ID（プライマリキー）"
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "顧客ID"
          - name: order_date
            description: "注文日"
          - name: order_amount
            description: "注文金額"
          - name: status
            description: "注文ステータス"
          - name: created_at
            description: "作成日時"
      
      - name: payments
        description: "支払いデータテーブル"
        columns:
          - name: payment_id
            description: "支払いID（プライマリキー）"
            tests:
              - unique
              - not_null
          - name: order_id
            description: "注文ID"
          - name: payment_type_code
            description: "支払い方法コード"
          - name: payment_method
            description: "支払い方法名"
          - name: amount
            description: "支払い金額"
          - name: payment_date
            description: "支払い日時"
          - name: created_at
            description: "作成日時"