version: 2

models:
  - name: stg_your_source_system__table1
    description: "ソースシステムのテーブル1をステージング"
    columns:
      - name: id
        tests:
          - not_null
          - unique
  - name: stg_payments
    description: "支払いデータをステージング"
    columns:
      - name: order_id
        tests:
          - not_null
